name: Greetings with Memes

on: [pull_request_target, issues]

jobs:
  greetings:
    runs-on: ubuntu-latest
    permissions:
      issue: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Memes
        run: |
          meme_files=($(find welcome_memes -type f))
          meme_count=${#meme_files[@]}
          random_index=$((RANDOM % meme_count))
          selected_meme=${meme_files[$random_index]}
          echo "::set-output name=selected_meme::$selected_meme"
        id: select_meme

      - name: Upload and Post Meme
        uses: actions/upload-artifact@v2
        with:
          name: welcome_meme
          path: ${{ steps.select_meme.outputs.selected_meme }}

      - name: Post Welcome Meme Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const memePath = '/github/workspace/' + process.env.RUNNER_OS + '/' + 'welcome_meme';
            const memeData = fs.readFileSync(memePath, 'base64');
            const issueComment = '![Welcome Meme](data:image/png;base64,' + memeData + ')\n\n' +
              'Welcome! We appreciate your contribution. ' +
              'Feel free to engage with our community and contribute further.';

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });

